spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/money_tracker
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=4F/oXzW6QwBfeeghf3RsQHJedD/NOV2RORgvi8u/BDE=
jwt.expiration=3600000